#pragma once
#include "addCircleCommand.h"
#include "addRectangleCommand.h"
#include "addTriangleCommand.h"
#include "changeFillColorCommand.h"
#include "changeOutlineColorCommand.h"
#include "changeOutlineThicknessCommand.h"
#include "undoCommand.h"
#include "saveToFileCommand.h"